### ISSUE TITLE
Force Final Evolution can make invalid Pokemon

### ISSUE THREAD

**Issue by m4-used-rollout** [ZadenOwer/randomizer-tool#28]
If the unevolved Pokemon (Sneasel, for example) has more forms than the evolved Pokemon (Weavile, for example), the randomizer can give trainers a Pokemon with an invalid form. This crashes the game.

Example: 
![image](https://user-images.githubusercontent.com/1911304/214854687-67893047-871e-4728-9753-17bb01e6fc98.png)

[Clip of a Twitch stream seeing it happen](https://clips.twitch.tv/BusyZanyFinchCharlietheUnicorn-Dlq21LyRz_leFR63) (this trainer's poke2 was Gallade)

**Comment by m4-used-rollout** [comment]
I think Wooper and Sneasel are the only ones at risk of this happening.

**Comment by ZadenOwer** [comment]
I see what is the problem here, I gonna work on fix that and release it on the next version, thanks for comment it

**Comment by ZadenOwer** [comment]
@m4-used-rollout I released a new version (1.1.6) with the fix, I validate to avoid invalid forms on the evolutions randomizer and the final evolutions checks

**Comment by m4-used-rollout** [comment]
@ZadenOwer I tested this just now and it's assigning an array instead of a number to formId making FlatC fail:

`Error creating binary for Trainers: b"\r\nerror:\r\n  \\randomizer-tool\\trdata_array.json(1, 226): error: Cannot assign token starting with '[' to value of <short> type.\r\n\r\n`

(1,226): `"formId": [0, "DEFAULT"]`

**Comment by m4-used-rollout** [comment]
It looks like getRandomForm now returns a tuple of form and sex, which [this line](https://github.com/ZadenOwer/randomizer-tool/blob/7730a361a54224a79a07cc0c5d5dc41154276270/src/scripts/randomizer/trainers.py#L375) fails to unpack.
It should probably be `randomizedTrainer[pokeKey]["formId"], randomizedTrainer[pokeKey]["sex"] = self.getRandomForm(dexId=finalEvo["dexId"], forms=finalEvo["forms"])`

**Comment by ZadenOwer** [comment]
oh sht you're right, I'll gonna make the hot fix and reupload the version
