### ISSUE TITLE
Issues and suggestions for the "Running the application locally" method

### ISSUE THREAD

**Issue by vincent0408** [ZadenOwer/randomizer-tool#32]
I just cloned the current code and it gave the
```
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\...\\logs\\log1675440450.29712.txt'
```
which can be solved by manually creating the ```logs``` folder or adding
```
import os
os.makedirs('./logs', exist_ok=True)
```
just thought I'd throw it out here although if anyone's using this method they probably know how to fix it anyways XD

Also unticking the randomize hidden items options throw
```
line 364, in <module>
    shutil.copy(f'./src/statics/{fileNames[fileName]}.bfbs', f'{paths[fileName]}/{fileNames[fileName]}.bfbs')
KeyError: 'hiddenItemData'
```
make it unable to not want this option
great work and thanks

**Comment by ZadenOwer** [comment]
Hello, I just pushed the fixes for those 2 bugs, thanks for the comment!
