### ISSUE TITLE
Zip file not generated

### ISSUE THREAD

**Issue by Xadovsk** [ZadenOwer/randomizer-tool#9]
The zip file was not generated at the last step. Don't if this is the cause, but i only randomized trainers and forced full team. Below is the screen shot.

![randomizerBug](https://user-images.githubusercontent.com/56688906/206447694-c898812d-7b2e-4b21-979c-aa72e0dbe19c.png)

**Comment by ZadenOwer** [comment]
Wow this is something from my side yeah, I gonna try to replicate it and fix it, stay tuned for the next releases

**Comment by ZadenOwer** [comment]
Ok I updated the last version, you can download it and try again

**Comment by Xadovsk** [comment]
It's working now, thanks!
